# Generated by Django 5.2.1 on 2026-04-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0004_folder_parent_alter_sharedfile_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='expiry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
